### ISSUE TITLE
Issue on page /ch_data_processing/pandas-profiling.html

### ISSUE THREAD

**Issue by tiepvupsu** [tiepvupsu/tabml_book#33]
Fix pandas-profiling html result https://htmlpreview.github.io/?https://github.com/tiepvupsu/tabml_book/blob/main/book/ch_data_processing/titanic_train_profiling.html#correlations_tab-cramers.

In each section, only the main tab works.

**Comment by dungxibo123** [comment]
If I'm not wrong, the "Toggle Details" is not working right, sir? I have downloaded the file to my laptop and run it in HTML, and it really works. I wonder if you reach the same problem.
`Edit`, I have some experiments until now

* Downloads HTML from your source and run it on my browser, That was normal, the other tabs still working
* Downloads HTML from `https://htmlpreview.github.io/?https://github.com/tiepvupsu/tabml_book/blob/main/book/ch_data_processing/titanic_train_profiling.html#overview-reproduction` to preview also in my browser. BUT THIS TIME, It doesn't contain any events.


Because of my experiments, I think the problems not on your code or on Pandas Profiling, It because of the `htmlpreview.github.io`

**Comment by tiepvupsu** [comment]
Thanks, I believe it's in the `htmlpreview.github.io`.

I have an idea of how to fix it, will update over the weekend.
